Nonpr 1717 upgrades
hmrc/nrs-retrieval-frontend pull request #97
Opened 2021-05-17 09:43 UTC by Leeroyc720

**Acceptance-tests results:** 

- 24 Scenarios (24 passed)
- 196 Steps (196 passed)
- Runtime: 4m1.908s

**Tests Results:** 

- [info] Run completed in 11 seconds, 86 milliseconds.
- [info] Total number of tests run: 53
- [info] Suites: completed 13, aborted 0
- [info] Tests: succeeded 53, failed 0, canceled 0, ignored 0, pending 0
- [info] All tests passed.
- [info] Passed: Total 53, Failed 0, Errors 0, Passed 53

2021-05-17 15:12 UTC, craigtd requested changes
Just a change to .gitignore required and remove .bsp dir from the PR

2021-05-17 15:12 UTC, craigtd commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.4.9","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/Use
@Leeroyc720 this file should not be included as part of the CR. Recommend you remove this and then ensure it is added correctly to your .gitignore file

2021-05-17 15:12 UTC, craigtd commented on .gitignore
> +/.bsp/
Doesn't look like this worked as planned. Propose follow this pattern: https://github.com/hmrc/nonrep-attachment-processor/blob/master/.gitignore#L16

2021-05-17 15:13 UTC, craigtd commented
There are some deprecation warnings - we can address these via a separate ticket @Leeroyc720

2021-05-17 15:14 UTC, craigtd commented
Confirmed all unit tests were successful and manually tested the frontend using service manager dependencies.

2021-05-17 15:55 UTC, Leeroyc720 commented on .bsp/sbt.json
> +{"name":"sbt","version":"1.4.9","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/Use
Thanks for spotting this, its now resolved

2021-05-17 15:59 UTC, craigtd approved these changes
Looks fine.

2021-05-17 16:05 UTC, merged

2021-05-17 16:12 UTC, greg-gajda commented on build.sbt
>    "com.typesafe.play" %% "play-json-joda" % "2.9.0",
There are more recent versions available for govuk-template, govuk-template and play-json-joda.
Is there any reason why we don;t update them?

2021-05-17 16:12 UTC, greg-gajda commented on build.sbt
> -  "uk.gov.hmrc" %% "hmrctest" % "3.9.0-play-26" % scope,
It looks like play-27 is used for application and play-26 for unit tests.
Shouldn't that be improved as well?

2021-05-17 16:12 UTC, greg-gajda commented on build.sbt
>    "org.scalatest" %% "scalatest" % "3.0.8" % scope,
3.2.9 is possibly the latest stable tag for scalatest.

2021-05-17 16:12 UTC, greg-gajda commented on project/build.properties
> -sbt.version=1.3.13
Why 1.4.9 instead of https://github.com/sbt/sbt/releases/tag/v1.5.2 ?

2021-05-18 08:05 UTC, Leeroyc720 commented on project/build.properties
> -sbt.version=1.3.13
Hi Greg, for most of these upgrades I was using these suggestions: https://catalogue.tax.service.gov.uk/service/nrs-retrieval-frontend

2021-05-18 08:12 UTC, Leeroyc720 commented on build.sbt
>    "com.typesafe.play" %% "play-json-joda" % "2.9.0",
I will  bump the play-ui version up, do you happen to have a link for the play-json-joda page as some of these dependencies don't get listed on the 'what's running where page?'

2021-05-18 08:35 UTC, Leeroyc720 commented on build.sbt
> -  "uk.gov.hmrc" %% "hmrctest" % "3.9.0-play-26" % scope,
That is the latest version that has been suggested, don't think they have play-27 versions for hmrctest released yet, been going through most repos it seems this the current latest that's being suggested to use.